var JE=window.JE||{};JE.url={'reg':'http://reg.justeasy.cn/','pic':'http://pic.justeasy.cn/','www':'index.htm'/*tpa=http://www.justeasy.cn/*/,'smallimg':'http://small.justeasy.cn/','bigimg':'http://big.justeasy.cn/','avatar':'http://big.justeasy.cn/avatar/','data':'http://data.justeasy.cn/','app':"http://api.justeasy.cn/",'res1':"http://res1.justeasy.cn/",'mall':"http://mall.justeasy.cn/",'vr':"http://vr.justeasy.cn/",'upfile':"http://upfile.justeasy.cn/"}
var submiting=0;$(function(){if(typeof lazyload!="undefined"){setTimeout(function(){$("img[sign='lazy']").lazyload({effect:"fadeIn"});},500);}
$("#searchbox-submit").click(function(event){var keywords=$("#searchbox-keywords").val();var type=0;type=$("#select-sub").val();$.getJSON(JE.url.data+'search.cgi?callback=?',{type:type,keywords:keywords},function(data,textStatus){if(data&&data.status==200){location=data.location;}});});$(document).keydown(function(event){var code=event.which;var keywords=$("#searchbox-keywords").val();if(keywords&&code==13&&$("#searchbox-keywords").is(":focus")){$("#searchbox-submit").click();}})
browsercheck();getuserinfo();});function layerLogin(obj,type){$.ajax({url:JE.url.data+"login.php",type:"POST",dataType:'jsonp',data:{obj:obj,type:type,},success:function(data,textStatus){lf=layer.open({type:1,title:false,closeBtn:0,area:['340px','380px'],content:data.message});}})}
function layerreg(obj,type,ltype){$.ajax({url:JE.url.data+"login.php",type:"POST",dataType:'jsonp',data:{obj:obj,type:type,ltype:ltype},success:function(data,textStatus){lf=layer.open({type:1,title:false,closeBtn:0,area:['340px','500px'],content:data.message});}})}
function layerAdvise(type){$.ajax({url:JE.url.data+"advise.php",type:"POST",dataType:'jsonp',data:{type:type},success:function(data,textStatus){lf=layer.open({type:1,title:'问题建议',area:['480px','500px'],content:data.message,'skin':'layui-custom'});}})}
function browsercheck(){var browserInfo={browser:"",version:""};var ua=navigator.userAgent.toLowerCase();if(window.ActiveXObject){browserInfo.browser="IE";browserInfo.version=ua.match(/msie ([\d.]+)/)[1];if(browserInfo.version<=8){alert('您的ie浏览器版本过低，建议使用chorme浏览器或升级到最新的IE版本');}}}
function getuserinfo(){$.getJSON(JE.url.data+'getLoginInfo.cgi?callback=?',function(json,textStatus){if(json&&json.status==200){var data=json.info;$("#nologin").remove();$("#haslogin").show();$("#msgbox").show();$("#managecenter").show();if(data.msgnum>0){$("#msgnum").text(data.msgnum);}else{$("#msgnum").hide();}
$("#nickname").text(data.nickname?data.nickname:data.username);var avatar=data.avatar;if(avatar==""||avatar==null||avatar=="null"){avatar=JE.url.res1+'images/defaulthead.jpg';}
if(avatar.indexOf("http://")>=0||avatar.indexOf("https://")>=0){avatar=avatar;}else{avatar=JE.url.avatar+avatar;}
$("#user-box-avatar").attr("src",avatar);$("#user-box-userid").text("建E号："+data.id);$("#user-box-grzy").attr("href",JE.url.vr+"designer/"+data.id+'.html');var isyear=data.isyear;if(isyear=="1"){$(".kt1").show();$(".kt2").hide();$("#fc999").text(data.yearenddate.slice(0,10))}else{$(".kt1").hide();$(".kt2").show();}
$("#user-box-point").text(Number(data.point).toFixed(1));$("#user-box-coin").text(data.ecoin);$("#nickname").text(data.nickname?data.nickname:data.username);}else{$("#nologin").show();}});};$(function(){var _objid=typeof commentobjid!="undefined"?commentobjid:0;var _type=typeof commentobjtype!="undefined"?commentobjtype:0;var _domid=typeof commentdomid!="undefined"?commentdomid:"";var _currpage=1;$(document).on('keyup','#comment-content',function(event){event.preventDefault();var v=$(this).val();if(v){$("#btn_submit_comment").addClass('active');}else{$("#btn_submit_comment").removeClass('active');}});getCommentList(_objid,_type,_currpage);function getCommentList(id,type,page){if(!_domid)return;if(page==1){var wrapper=$('<div class="comment-wrapper" id="comment-wrapper">');$('<div class="comment-box" id="commentaddbox" style="padding-bottom: 35px;">'+'<div class="header">'+'<h3>全部评论</h3><span class="commentnum">( <span class="comment_num"> </span> )</span>'+'</div>'+'<div class="input-box">'+'<input type="text" class="input-text" id="comment-content" maxlength="500">'+'</div>'+'<div class="submit-box">'+'<div class="face">添加表情</div>'+'<div class="submit">'+'<input type="button" class="btn-submit" value="评 论" id="btn_submit_comment">'+'</div>'+'</div>'+'</div> <div class="comment-box"><ul class="commentlist" id="commentlist"></ul></div><div class="comment-more" id="comment-more">查看更多评论</div>').appendTo(wrapper);wrapper.appendTo(_domid);}
$.getJSON(JE.url.data+'service/cget.cgi?callback=?',{ajax:1,action:'home.get.comment',objid:id,page:page,type:type},function(data,textStatus){if(data&&data.status==200){$(".comment_num").text(data.count);var totalpage=data.totalpage;if(totalpage>page){$("#comment-more").show();}else{$("#comment-more").text("全部评论加载完成！").attr("finish","1");}
var commentlist="";if(data.hotinfo.length>0&&$("#hot-comment").length==0){var hotlist='<div class="comment-box"><ul class="commentlist" id="hot-comment"></ul><div class="hotdes"><span>以上为精选评论</span></div></div>';$("#commentaddbox").after(hotlist);$.each(data.hotinfo,function(index,val){var reply=val.reply;var replylist="";if(reply.length>0){$.each(reply,function(i,v){replylist+='<li class="comment-item">'+'<div class="replybox">'+' <div class="userinfo">'+'  <span class="nickname"><a href="'+JE.url.vr+'designer/'+v.uid+'/'+_type+'.html" target="_blank">'+v.nickname+'</a></span>'+'  <span class="devide">|</span>'+'  <span class="date">'+timeDiff(v.addtime)+'</span>'+'  <span class="reply" type="2" data='+val.id+'>回复</span>'+' </div>'+' <div class="contentbox">'+'  <div class="content">'+v.content+'  </div>'+' </div>'+'</div>'+'</li>';});}
commentlist+='<li class="comment-item">'+'<div class="avatar">'+' <a href="'+JE.url.vr+'designer/'+val.uid+'/'+_type+'.html" target="_blank"><img src="'+getHead(val.avatar)+'"></a>'+'</div>'+'<div class="conmentbox">'+' <div class="userinfo">'+'  <span class="nickname"><a href="'+JE.url.vr+'designer/'+val.uid+'/'+_type+'.html" target="_blank">'+val.nickname+'</a></span>'+'  <span class="devide">|</span>'+'  <span class="date">'+timeDiff(val.addtime)+'</span>'+'  <span class="reply" type="1" data='+val.id+'>回复 ( <span id="replynum">'+val.reply_nums+'</span> )</span>'+' </div>'+' <div class="contentbox" id="contentbox_'+val.id+'">'+'  <div class="content">'+val.content+'  </div><ul class="replylist" id="replylist_'+val.id+'">'+
(replylist!=""?replylist:"")+' </ul></div>'+'</div>'+'</li>';});$(commentlist).appendTo("#hot-comment");}
commentlist="";$.each(data.info,function(index,val){var reply=val.reply;var replylist="";if(reply.length>0){$.each(reply,function(i,v){replylist+='<li class="comment-item">'+'<div class="replybox">'+' <div class="userinfo">'+'  <span class="nickname"><a href="'+JE.url.vr+'designer/'+v.uid+'/'+_type+'.html" target="_blank">'+v.nickname+'</a></span>'+'  <span class="devide">|</span>'+'  <span class="date">'+timeDiff(v.addtime)+'</span>'+'  <span class="reply" type="2" data='+val.id+'>回复</span>'+' </div>'+' <div class="contentbox">'+'  <div class="content">'+v.content+'  </div>'+' </div>'+'</div>'+'</li>';});}
commentlist+='<li class="comment-item">'+'<div class="avatar">'+' <a href="'+JE.url.vr+'designer/'+val.uid+'/'+_type+'.html" target="_blank"><img src="'+getHead(val.avatar)+'"></a>'+'</div>'+'<div class="conmentbox">'+' <div class="userinfo">'+'  <span class="nickname"><a href="'+JE.url.vr+'designer/'+val.uid+'/'+_type+'.html" target="_blank">'+val.nickname+'</a></span>'+'  <span class="devide">|</span>'+'  <span class="date">'+timeDiff(val.addtime)+'</span>'+'  <span class="reply" type="1" data='+val.id+'>回复 ( <span id="replynum">'+val.reply_nums+'</span> )</span>'+' </div>'+' <div class="contentbox" id="contentbox_'+val.id+'">'+'  <div class="content">'+val.content+'  </div><ul class="replylist" id="replylist_'+val.id+'">'+
(replylist!=""?replylist:"")+' </ul></div>'+'</div>'+'</li>';});$(commentlist).appendTo("#commentlist");}});}
$(document).on('click','.reply',function(event){event.preventDefault();var obj=$(this);var type=obj.attr("type");var commentid=obj.attr("data");var nickname="",nickname2="";if(type=="2"){nickname=obj.parent().find(".nickname").text();nickname2='@'+obj.parent().find(".nickname").text()+'： ';}
$(".addreplybox").remove();var replybox='<div class="addreplybox">'+'  <div class="input-box">'+'   <input type="text" class="input-text" id="reply-content" maxlength="500" value="'+nickname2+'" commentid="'+commentid+'" nickname="'+nickname+'">'+'  </div>'+'  <div class="submit-box">'+'   <div class="face">'+'    添加表情'+'   </div>'+'   <div class="submit">'+'    <a href="javascript:;" onclick="$(this).parent().parent().parent().remove();" class="btn_cancel">取 消</a>&nbsp;&nbsp;&nbsp;'+'    <input type="button" class="btn-submit active" value="回 复" id="btn_submit_reply">'+'   </div>'+'  </div>'+' </div>';$("#contentbox_"+commentid).after(replybox);});$(document).on('click','#btn_submit_reply',function(event){event.preventDefault();var comment=$("#reply-content").val();var commentid=$("#reply-content").attr("commentid");var nickname=$("#reply-content").attr("nickname");if(comment==""){layer.msg("请填写回复内容！");return;}
comment=comment.replace("@"+nickname+"：",'<span class="nickname">@'+nickname+'：</span>');if(isNaN(commentid)){layer.msg("参数错误！");return;}
$.getJSON(JE.url.data+'service/cadd.cgi?callback=?',{ajax:1,action:"home.add.comment",objid:commentid,comment:comment,reply:2,type:_type,modelid:_objid},function(data,textStatus){if(data.code==-1001){layerLogin();return;}
if(data.code==3000){layer.msg("回复成功！");$(".addreplybox").remove();var replylist='<li class="comment-item">'+' <div class="replybox">'+'  <div class="userinfo">'+'   <span class="nickname"><a href="'+JE.url.vr+'designer/'+data.uid+'/'+_type+'.html" target="_blank">'+data.nickname+'</a></span>'+'   <span class="devide">|</span>'+'   <span class="date">刚刚</span>'+'   <span class="reply" type="2" data='+commentid+'>回复</span>'+'  </div>'+'  <div class="contentbox">'+'   <div class="content">'+comment+'   </div>'+'  </div>'+' </div>'+'</li>';$("#replylist_"+commentid).append(replylist);}else{layer.msg("回复失败！");}});});$(document).on('click','#btn_submit_comment',function(event){event.preventDefault();var comment=$("#comment-wrapper #comment-content").val();if(comment==""){return;}
$.getJSON(JE.url.data+'service/cadd.cgi?callback=?',{ajax:1,action:"home.add.comment",objid:_objid,comment:comment,reply:1,type:_type,modelid:_objid},function(data,textStatus){if(data.code==-1001){layerLogin();return;}
if(data.code==3000){layer.msg("评论成功！");var commentlist='<li class="comment-item">'+'<div class="avatar">'+' <a href="'+JE.url.vr+'designer/'+data.uid+'/'+_type+'.html" target="_blank"><img src="'+getHead(data.avatar)+'"></a>'+'</div>'+'<div class="conmentbox">'+' <div class="userinfo">'+'  <span class="nickname"><a href="'+JE.url.vr+'designer/'+data.uid+'/'+_type+'.html" target="_blank">'+data.nickname+'</a></span>'+'  <span class="devide">|</span>'+'  <span class="date">刚刚</span>'+'  <span class="reply" type="1" data='+data.id+'>回复 ( <span id="replynum">0</span> )</span>'+' </div>'+' <div class="contentbox" id="contentbox_'+data.id+'">'+'  <div class="content">'+comment+'  </div><ul class="replylist" id="replylist_'+data.id+'">'+' </ul></div>'+'</div>'+'</li>';$("#commentlist").prepend(commentlist);$("#comment-wrapper #comment-content").val('');$("#comment-wrapper #btn_submit_comment").removeClass('active');$(".comment_num").text(parseInt($(".comment_num").eq(0).text())+1);}else{layer.msg("评论失败！");}});});$(document).on('click','#comment-more',function(event){event.preventDefault();var isfinish=$(this).attr("finish");if(!isfinish){_currpage++;getCommentList(_objid,_type,_currpage);}});})
function comment_other(_objid,_type,commenttextid){event.preventDefault();var comment=$(commenttextid).val();if(comment==""){return;}
$.getJSON(JE.url.data+'service/cadd.cgi?callback=?',{ajax:1,action:"home.add.comment",objid:_objid,comment:comment,reply:1,type:_type,modelid:_objid},function(data,textStatus){if(data.code==-1001){layerLogin();return;}
if(data.code==3000){layer.msg("评论成功！");var commentlist='<li class="comment-item">'+'<div class="avatar">'+'   <img src="'+getHead(data.avatar)+'">'+'</div>'+'<div class="conmentbox">'+'   <div class="userinfo">'+'       <span class="nickname">'+data.nickname+'</span>'+'       <span class="devide">|</span>'+'       <span class="date">刚刚</span>'+'       <span class="reply" type="1" data='+data.id+'>回复 ( <span id="replynum">0</span> )</span>'+'   </div>'+'   <div class="contentbox" id="contentbox_'+data.id+'">'+'       <div class="content">'+comment+'       </div><ul class="replylist" id="replylist_'+data.id+'">'+'   </ul></div>'+'</div>'+'</li>';$("#commentlist").prepend(commentlist);$(commenttextid).val('');$(".comment_num").text(parseInt($(".comment_num").eq(0).text())+1);$(".comments-box").css("display",'none');$("#like2").addClass('border-bottom-n');}else{layer.msg("评论失败！");}});}
function againcutpic(){layer.close(lf9);$('.img-wrapper-join').click();}
function effecttool(img,width,height){if(width==0||height==0){layer.msg('裁剪失败');return false;}
layer.close(lf8);var html=$('#div_tool_tpl').html();;lf9=layer.open({type:1,title:'添加效果图',area:['830px','620px'],content:html});$('#collectionids').chosen({width:'320'});if(width>height){width1=226;height1=height*(226/width);$("#effectimg").attr('src',JE.url.bigimg+img).width(width1).height(height1).css('margin-top',(226-height1)/2);}else{height1=226;width1=width*(226/height);marg2=(226-width1)/2;$("#effectimg").attr('src',JE.url.bigimg+img).width(width1).height(height1).css('margin-left',(226-width1)/2);}
$("#img").val(img);$("#ewidth").val(width);$("#eheight").val(height);$.ajax({url:JE.url.www+'/effecttool/getlist.php',type:'post',dataType:'json',data:{1:1}}).done(function(data){if(data&&data.status==200)
{var option="<option value='0'>选择效果图方案</option>";$.each(data.list,function(index,val){option+="<option value='"+val.id+"'>"+val.title+"</option>"});$('#collectionids').html(option);$('#collectionids').trigger('chosen:updated')}}).fail(function(){}).always(function(){});}
function createToole(){var etitle=$("#etitle").val();if(!etitle){layer.msg('请输入效果图方案名称');return;}
$.ajax({url:JE.url.www+'/effecttool/createtool.php',type:'post',dataType:'json',data:{title:etitle}}).done(function(data){if(data&&data.status==200){layer.msg(data.msg);$("#etitle").val('');$("#eabstract").val('');var option="<option value='"+data.list.id+"'>"+data.list.title+"</option>"
$('#collectionids').append(option);$('#collectionids').trigger('chosen:updated')}else if(data&&data.status==-201){layerLogin('createToole',2);}else{layer.msg(data.msg);}}).fail(function(){}).always(function(){});}
function addeffectpic(type){var collectionids=$("#collectionids").val();if(!collectionids||collectionids==0||collectionids=='0'){layer.msg("请选择效果图方案！");return;}
var eabstract=$("#eabstract").val();if(!eabstract){layer.msg('请输入效果图细节描述');return;}
var img=$("#img").val();var ewidth=$("#ewidth").val();var eheight=$("#eheight").val();if(!img){layer.msg('参数异常');return;}
$.ajax({url:JE.url.www+'/effecttool/addeffectpic.php',type:'post',dataType:'json',data:{collectionids:collectionids,img:img,ewidth:ewidth,eheight:eheight,obj:commentobjid,eabstract:eabstract,type:type}}).done(function(data){if(data&&data.status==200){layer.msg(data.msg,{time:2000},function(){layer.close(lf9);});}else if(data&&data.status==-201){layerLogin('createToole',2);}else{layer.msg(data.msg);}}).fail(function(){}).always(function(){});}
function updatetool(){var collectionids=$("#collectionids").val();if(!collectionids||collectionids=='0'||collectionids==0){layer.msg("请选择效果图方案！");return false;}
location.href=JE.url.reg+"user/effecttool/addeffecttool.php?id="+collectionids;}
function initpos(obj,type){var img=new Image();img.onload=function(){var imgwidth=parseInt(img.width);var imgheight=parseInt(img.height);if(type==1){var simgwidth=810;var simgheight=615;}else{var simgwidth=$(obj).parent().parent().width();var simgheight=$(obj).parent().parent().height();}
if(imgwidth/imgheight>(simgwidth/simgheight)){var timgwidth=simgwidth;var timgheight=simgwidth*imgheight/imgwidth
$(obj).width(simgwidth);$(obj).height(simgwidth*imgheight/imgwidth);}else{var timgheight=simgheight;var timgwidth=simgheight*imgwidth/imgheight}
$(obj).width(timgwidth);$(obj).height(timgheight);$(obj).css('margin-left',((simgwidth/2)-(timgwidth/2))+"px");$(obj).css('margin-top',((simgheight/2)-(timgheight/2))+"px");$(obj).show();};img.src=$(obj).attr('src');}
function getAllView(obj,type){var ids='';obj.each(function(i){ids+=$(this).attr('rel')+',';});ids=ids.substring(0,ids.length-1)
if(ids){$.ajax({url:JE.url.data+'service/cget.cgi?callback=?',type:"GET",async:false,dataType:'jsonp',data:{action:'home.get.token',id:ids},success:function(data,textStatus){if(data.code==2002){var token=data.token.toUpperCase();$.getJSON(JE.url.data+'/getallviewnum.cgi?callback=?',{ids:ids,type:type,token:token},function(json1,textStatus){var list=json1.list;obj.each(function(i){if(list[i]=='false'||!list[i]){$(this).text(0);}else{$(this).text(list[i]);}});});}}})}}
function addlike(objid,type){if(submiting==0){submiting=1;var action='';if(type=='model'){action='home.upd.modellike';}else if(type=='map'){action='home.upd.maplike';}else if(type=='cad'){action='home.upd.cadlike';}
$.ajax({url:JE.url.data+'service/cupd.cgi?callback=?',type:"GET",async:false,dataType:'jsonp',data:{ajax:1,action:action,objid:objid,type:type},success:function(data,textStatus){submiting=0;if(data.code==-1001){layer.msg('请登录后点赞，正在为您跳转至登录页面',{time:1000},function(){if(data.type=='model'){location=je.url.reg+"/login.html?backurl="+je.url.www+'/3d/id-'+data.objid+'.html';}else if(data.type=='map'){location=JE.url.reg+ +"/login.html?backurl="+je.url.www+'/tietu/detail/'+data.objid+'.html';}else if(data.type=='cad'){location=je.url.reg+"/login.html?backurl="+je.url.www+'/cad/id-'+data.objid+'.html';}else{location=je.url.reg+"/login.html?backurl=";}});}else if(data.code==4001){var num=$("#like_num").text();num=Number(num)+1;$("#like_num").text(num);$('#like_active').addClass('active');$('#modellikenum').removeClass('icon-likeed-h').addClass('icon-likeed');layer.msg('点赞成功',{time:1000},function(){});}else{layer.msg(data.msg,{time:1000});}}})}}
$(function(){$("img[data-sign='lazy']").addClass('lazy-bg').lazyload({effect:"fadeIn",skip_invisible:false,threshold:200});});function getModelViewAll(obj,type){var ids='';obj.each(function(i){ids+=$(this).attr('rel')+',';});ids=ids.substring(0,ids.length-1);if(!ids){return false;}
$.ajax({url:JE.url.data+'/service/cget.cgi?callback=?',type:"GET",async:false,dataType:'jsonp',data:{action:'home.get.token',id:ids},}).done(function(data){if(data.code==2002){var token=data.token.toUpperCase();$.ajax({url:JE.url.data+'/getallviewnum.cgi?callback=?',type:"GET",async:false,dataType:'jsonp',data:{ids:ids,type:type,token:token},}).done(function(data){var list=HandleNums(data.list);obj.each(function(i){if(list[i]=='false'||!list[i]){$(this).text(0);}else{$(this).text(list[i]);}});}).fail(function(){});}}).fail(function(){return false;});}
function ImgPosInit(obj,type){var img=$(obj);if(typeof obj.naturalWidth!="undefined"){var realWidth=obj.naturalWidth;var realHeight=obj.naturalHeight;var standwidth=$(obj).parent().parent().width();var standheight=$(obj).parent().parent().height();if(type==2){if(realWidth>realHeight){img.width(standwidth);img.height(img.width()*realHeight/realWidth);}else{img.height(standheight);img.width(img.height()*realWidth/realHeight);}}else if(type==3){if(realWidth>realHeight){img.width(standwidth);img.height(img.width()*realHeight/realWidth);}else{img.height(standheight);img.width(img.height()*realWidth/realHeight);}}else{if((realWidth/realHeight)>=(standwidth/standheight)){if(realHeight<standheight){img.height(standheight);img.width(img.height()*realWidth/realHeight);}else{img.width(realWidth);img.height(realHeight);}
if(type==1&&realHeight>standheight){img.height(standheight);img.width(img.height()*realWidth/realHeight);}}else{if(realWidth<standwidth){img.width(standwidth);img.height(img.width()*realHeight/realWidth);}else{img.width(realWidth);img.height(realHeight);}
if(type==1&&realWidth>standwidth){img.width(standwidth);img.height(img.width()*realHeight/realWidth);}}}
img.css("margin-top",-(img.height()-standheight)/2);img.css("margin-left",-(img.width()-standwidth)/2);}else{var imageobj=new Image();imageobj.onload=function(){var realWidth=imageobj.width;var realHeight=imageobj.height;var standwidth=$(obj).parent().parent().width();var standheight=$(obj).parent().parent().height();if(type==2){if(realWidth>realHeight){img.width(standwidth);img.height(img.height()*realHeight/realWidth);}else{img.height(standheight);img.width(img.width()*realWidth/realHeight);}}else{if((realWidth/realHeight)>=(standwidth/standheight)){if(realHeight<standheight){img.height(standheight);img.width(img.height()*realWidth/realHeight);}else{img.width(realWidth);img.height(realHeight);}
if(type==1&&realHeight>standheight){img.height(standheight);img.width(img.height()*realWidth/realHeight);}}else{if(realWidth<standwidth){img.width(standwidth);img.height(img.width()*realHeight/realWidth);}else{img.width(realWidth);img.height(realHeight);}
if(type==1&&realWidth>standwidth){img.width(standwidth);img.height(img.width()*realHeight/realWidth);}}}
img.css("margin-top",-(img.height()-standheight)/2);img.css("margin-left",-(img.width()-standwidth)/2);}
imageobj.src=obj.src;}}
function getModelDownAll(obj){var ids='';obj.each(function(i){ids+=$(this).attr('rel')+',';});ids=ids.substring(0,ids.length-1);if(!ids){return false;}
$.ajax({url:JE.url.data+'/service/cget.cgi?callback=?',type:"GET",async:false,dataType:'jsonp',data:{action:'home.get.token',id:ids},}).done(function(data){if(data.code==2002){var token=data.token.toUpperCase();$.ajax({url:JE.url.data+'/getAllDownView.cgi?callback=?',type:"GET",async:false,dataType:'jsonp',data:{ids:ids,token:token},}).done(function(data){var list=HandleNums(data.list);obj.each(function(i){if(list[i]=='false'||!list[i]){$(this).text(0);}else{$(this).text(list[i]);}});}).fail(function(){});}}).fail(function(){return false;});}
function HandleNums(list){$.each(list,function(i,item){item=parseInt(item);if(item>100000){list[i]='10万+';}else if(item>=10000&&item<=100000){list[i]=(item/10000).toFixed(2)+'万';}else{list[i]=item;}});return list;};function checkEmail(strEmail){var emailReg=/^[\w-]+(\.[\w-]+)*@[\w-]+(\.[\w-]+)+$/;return emailReg.test(strEmail);}
function checkPhone(strPhone){var phoneReg=/^[1][3,4,5,6,7,8,9][0-9]{9}$/;return phoneReg.test(strPhone);}
function checkQQ(strQQ){var QQReg=/^[1-9]\d{4,12}$/;return QQReg.test(strQQ);}
function isURL(url){var strRegex="^((https|http)://)?[0-9a-zA-Z-]+\.?\\w*?\.\\w{2,5}(:[0-9]{1,6})?";var re=new RegExp(strRegex);if(re.test(url)){return true;}else{return false;}}
function checkPassword(pwd){var result=new Object();result.result=true;if(!pwd){result.result=false;result.tips="请输入密码";return result;}
if(pwd.length<6||pwd.length>20){result.result=false;result.tips="请输入6-20位字母和数字的组合";return result;}
if(/^[0-9]{6,20}$/.exec(pwd)){result.result=false;result.tips="请使用字母和数字组合";return result;}
if(/^[a-zA-Z]{6,20}$/.exec(pwd)){result.result=false;result.tips="请使用字母和数字组合";return result;}
if(!/^[a-zA-Z0-9]{6,20}$/.exec(pwd)){result.result=false;result.tips="请使用字母和数字组合";return result;}
return result;}
function getQueryStringByName(name){var result=location.search.match(new RegExp("[\?\&]"+name+"=([^\&]+)","i"));if(result==null||result.length<1){return"";}
return result[1];}
function G(name){return getQueryStringByName(name);}
function timeDiff(time){if(!time)return;var otime=0;if(isNaN(time)){time=time.replace(/-/g,'/');otime=(new Date(time)).getTime();}else{otime=time*1000;}
if(!otime)return;var now=new Date().getTime();var diff=(now-otime)/1000;var chunks=[[31536000,'年'],[2592000,'个月'],[604800,'周'],[86400,'天'],[3600,'小时'],[60,'分钟'],[1,'秒']];var num=0,since="";for(var i=0;i<chunks.length;i++){if(diff>chunks[i][0]){num=Math.floor(diff/chunks[i][0]);since+=num+chunks[i][1];diff=parseInt(diff-chunks[i][0]*num);break;}}
if(since=="")return"刚刚";return since+"前";}
function getHead($url){if(!$url){return JE.url.res1+'images/defaulthead.jpg';}
if($url.indexOf("http://")>=0||$url.indexOf("https://")>=0){return $url;}else{return JE.url.avatar+$url;}}
function getEwmHead($url){if(!$url){return JE.url.res1+'images/reg/e.png';}
if($url.indexOf("http://")>=0||$url.indexOf("https://")>=0){return $url;}else{return JE.url.avatar+$url;}}
function secondToTime(unixTime,isFull,timeZone){if(typeof(timeZone)=='number'){unixTime=parseInt(unixTime)+parseInt(timeZone)*60*60;}
var time=new Date(unixTime*1000);var ymdhis="";ymdhis+=time.getUTCFullYear()+"-";ymdhis+=(time.getUTCMonth()+1)+"-";ymdhis+=time.getUTCDate();if(isFull===true){ymdhis+=" "+time.getUTCHours()+":";ymdhis+=time.getUTCMinutes()+":";ymdhis+=time.getUTCSeconds();}
return ymdhis;}
function htmlencode(s){var div=document.createElement('div');div.appendChild(document.createTextNode(s));return div.innerHTML;}
function htmldecode(s){return s.replace(/&#60;/g,'<').replace(/&#62;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'/"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,'"');}
function orientation(){if(window.orientation==90||window.orientation==-90){$("body").attr("class","landscape");return false;}else if(window.orientation==0||window.orientation==180){$("body").attr("class","portrait");return false;}}